### ISSUE TITLE
bug in RTL and using another fonts

### ISSUE THREAD

**Issue by pejman-hkh** [satya164/react-simple-code-editor#131]
### Current behaviour
In RTL direction and using another fonts this editor not work properly, I solved it with some extra CSS :

```css
.simple-editor * {
    direction: ltr !important;
    text-align: left !important;
    font-family: "Fira code", "Fira Mono", monospace !important;
}
```
