### ISSUE TITLE
How to remove the thin blue border?

### ISSUE THREAD

**Issue by colms** [satya164/react-simple-code-editor#48]
I'm sure I'm doing something wrong because the editor on your homepage has no borders.

### Current behaviour

A thin blue border appears around the outside of the editor even when border is set to 0.

### Expected behaviour

Border should follow the specified style and disappear.

### Code sample

```
<Editor
        value={props.headers}
        onValueChange={code => props.onHeadersChange(code)}
        highlight={code => highlight(code, languages.js, "javascript")}
        padding={10}
        style={{
          fontFamily: '"Fira code", "Fira Mono", monospace',
          border: "0px",
          borderWidth: 0
        }}
      />
```

### Screenshot

https://imgur.com/TQMnSTy

### What have you tried

Different style overrides.

### Your Environment

| software                 | version
| -------------------------| -------
| react-simple-code-editor |0.10.0
|prismjs|1.17.1
| react                    |16.10.2
| npm or yarn              |6.9.0
| node                     |10.16.3
| browser                  |chrome

**Comment by satya164** [comment]
That's browser's focus outline. You can remove it by applying `outline: 0` to the `textarea`, but make sure to have alternate styling for focus if you want your site to be successful.

Example:

```css
.editor textarea {
  outline: 0;
}
```

**Comment by colms** [comment]
Thanks for your help.

**Comment by jasonterando** [comment]
In case it helps anybody... I ran across a similar issue (my border was orange in Electron instead of blue).  Here is the CSS I used to make the border consistent with other MUI controls:

```css
.code-editor {
    outline: none;
    border: 1px !important;
    border-color: #444;
    border-width: 1px;
    border-radius: 4px;
    border-top-style: solid !important;
    border-bottom-style: solid !important;
    border-left-style: solid !important;
    border-right-style: solid !important;
}

.code-editor:focus {
    border-color: #90CAF9;
}
```

The !important after "border" is there because there is a "border: 0" added to the textarea when the library is rendering it.

To make this work you have to add a class to the editor's textarea:

```js
          <Editor
            autoFocus
            padding={10}
            textareaClassName='code-editor'
            value={body ?? ""}
            style={{
              height: '400px',
              fontFamily: 'monospace'
            }}
            highlight={code => processHighlight(code)}
            onValueChange={updateBody}
          />
```
